# Generated by Django 5.1.8 on 2025-05-07 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_name',
            field=models.CharField(default='My Site', max_length=100),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
